spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://10.101.132.249:7432/postgres
      username: postgres
      password: Bac12345
    jpa:
      properties.hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate:
        ddl-auto: validate